quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.h2.console.enabled=true
quarkus.datasource.h2.console.path=/h2-console
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:quarkus_db
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.hibernate-orm.database.generation=drop-and-create